import { PlanType, Task } from "./types";

// Database of all 5 Herbalife Routine plans extracted from PDF
export const DIET_PLANS: Record<PlanType, {
  nameEn: string;
  nameHi: string;
  targetEn: string;
  targetHi: string;
  tasks: Task[];
  guidelinesEn: string[];
  guidelinesHi: string[];
  forbiddenEn: string[];
  forbiddenHi: string[];
}> = {
  [PlanType.KIDS_PROGRESS]: {
    nameEn: "Kids Health and Growth Routine",
    nameHi: "किड्स हेल्थ & ग्रोथ रुटीन",
    targetEn: "Healthy Habit, Strong Immunity, Proper Nutrition, Active Lifestyle, Balanced Growth",
    targetHi: "स्वस्थ बच्चे, लंबाई में वृद्धि, सही वजन, मजबूत इम्युनिटी, एक्टिव लाइफस्टाइल",
    tasks: [
      {
        id: "kids-0630-water",
        time: "06:30 AM",
        hour: 6,
        minute: 30,
        titleEn: "Lukewarm Water",
        titleHi: "गुनगुना पानी",
        descriptionEn: "Drink 1 glass of lukewarm water right after waking up.",
        descriptionHi: "उठने के बाद 1 गिलास गुनगुना पानी पिएं।",
        isHerbalifeProduct: false,
        noCameraNeeded: false,
        healthyAlternatives: ["Water", "Coconut Water"],
      },
      {
        id: "kids-0700-activity",
        time: "07:00 AM",
        hour: 7,
        minute: 0,
        titleEn: "Morning Activity",
        titleHi: "मॉर्निंग एक्टिविटी",
        descriptionEn: "Exercise, Yoga, or Stretching to activate kids' bodies.",
        descriptionHi: "स्ट्रेचिंग, जॉगिंग या हल्का व्यायाम शरीर को फुर्तीला बनाने के लिए।",
        isHerbalifeProduct: false,
        noCameraNeeded: false,
      },
      {
        id: "kids-0730-breakfast",
        time: "07:30 AM",
        hour: 7,
        minute: 30,
        titleEn: "Healthy Breakfast (DinoShake)",
        titleHi: "हेल्दी ब्रेकफास्ट (DinoShake)",
        descriptionEn: "Delicious DinoShake nutritional mix + Milk + Banana for growth and nutrition.",
        descriptionHi: "DinoShake न्यूट्रिशनल शेक मिक्स + दूध + केला। बच्चों की हेल्दी ग्रो के लिए।",
        isHerbalifeProduct: true,
        requiredProduct: "DinoShake",
        noCameraNeeded: false,
      },
      {
        id: "kids-1000-snack",
        time: "10:00 AM",
        hour: 10,
        minute: 0,
        titleEn: "Seasonal Fruits Snack",
        titleHi: "स्कूल / मौसमी फल स्नैक",
        descriptionEn: "Eat seasonal fresh fruits and 4-5 almonds.",
        descriptionHi: "मौसमी ताजे फल खाएं और साथ में 4-5 नट्स या बादाम लें।",
        isHerbalifeProduct: false,
        noCameraNeeded: false,
        healthyAlternatives: ["Apple", "Banana", "Orange", "Papaya", "Almonds"],
      },
      {
        id: "kids-1300-lunch",
        time: "01:00 PM",
        hour: 13,
        minute: 0,
        titleEn: "Lunch",
        titleHi: "दोपहर का भोजन (लंच)",
        descriptionEn: "Eat 2 Roti + Vegetables + Dal + Salad + Curd.",
        descriptionHi: "2 रोटी + मौसमी सब्जी + दाल + ताज़ा सलाद + गाढ़ा दही।",
        isHerbalifeProduct: false,
        noCameraNeeded: false,
        healthyAlternatives: ["Rice with Dal/Vegs", "Roti-Veg-Curd"],
      },
      {
        id: "kids-1400-evening-snack",
        time: "02:00 PM",
        hour: 14,
        minute: 0,
        titleEn: "Evening Snack",
        titleHi: "लाइट हेल्दी स्नैक",
        descriptionEn: "Eat banana, roasted chickpeas (Chana), or Makhana.",
        descriptionHi: "केला, सेब, भुना हुआ चना या मखाना खाएं।",
        isHerbalifeProduct: false,
        noCameraNeeded: false,
        healthyAlternatives: ["Chana", "Makhana", "Banana", "Apple"],
      },
      {
        id: "kids-1600-sprouts",
        time: "04:00 PM",
        hour: 16,
        minute: 0,
        titleEn: "Evening Nutrition",
        titleHi: "इवनिंग न्यूट्रिशन",
        descriptionEn: "Sprouts, chickpeas, peanuts, or fruits for high energy.",
        descriptionHi: "स्प्राउट्स, मूंग, पीनट चिक्की या फल लें ताकि ऊर्जा बनी रहे।",
        isHerbalifeProduct: false,
        noCameraNeeded: false,
        healthyAlternatives: ["Sprouts", "Peanuts", "Fruit Salad"],
      },
      {
        id: "kids-1700-play",
        time: "05:00 PM",
        hour: 17,
        minute: 0,
        titleEn: "Outdoor Play Time",
        titleHi: "आउटडोर प्ले टाइम",
        descriptionEn: "Sports, Cycling, or running outdoor games for 45-60 minutes.",
        descriptionHi: "मैदान में दौड़ना, साइकिलिंग करना या आउटडोर गेम्स खेलना (45-60 मिनट)।",
        isHerbalifeProduct: false,
        noCameraNeeded: false,
      },
      {
        id: "kids-1800-aloe",
        time: "06:00 PM",
        hour: 18,
        minute: 0,
        titleEn: "Aloe Support (Herbal Aloe)",
        titleHi: "डाइजेशन सपोर्ट (Herbal Aloe)",
        descriptionEn: "Dilute Herbal Aloe Concentrate in water to support digestion & hydration.",
        descriptionHi: "Herbal Aloe कंसंट्रेट पानी में मिलाकर पिएं। पाचन सपोर्ट और हाइड्रेशन के लिए।",
        isHerbalifeProduct: true,
        requiredProduct: "Herbal Aloe Concentrate",
        noCameraNeeded: false,
      },
      {
        id: "kids-1930-dinner",
        time: "07:30 PM",
        hour: 19,
        minute: 30,
        titleEn: "Healthy Dinner",
        titleHi: "डिनर (रात का भोजन)",
        descriptionEn: "Eat Roti + Vegetables (Keep it simple & wholesome).",
        descriptionHi: "रोटी + हरी सब्जी। सादा और पोषण से भरपूर भोजन।",
        isHerbalifeProduct: false,
        noCameraNeeded: false,
        healthyAlternatives: ["Roti-Veg", "Khichdi", "Light Salad"],
      },
      {
        id: "kids-2100-milk",
        time: "09:00 PM",
        hour: 21,
        minute: 0,
        titleEn: "Good Nutrition Sleep Prep",
        titleHi: "नाइट न्यूट्रिशन (दूध)",
        descriptionEn: "Drink 1 glass of warm milk before head-to-bed sleep.",
        descriptionHi: "सोने से पहले 1 गिलास गुनगुना दूध पिएं।",
        isHerbalifeProduct: false,
        noCameraNeeded: false,
        healthyAlternatives: ["Milk", "Warm water"],
      },
      {
        id: "kids-2130-sleep",
        time: "09:30 PM",
        hour: 21,
        minute: 30,
        titleEn: "Sleep & Growth Recovery",
        titleHi: "नींद व आराम (Sleep)",
        descriptionEn: "Deep sleep 9-10 hours daily. Growth happens during sound sleep.",
        descriptionHi: "गहरी 9-10 घंटे की नींद लें। नींद में ही बच्चों का विकास होता है।",
        isHerbalifeProduct: false,
        noCameraNeeded: true, // Sleep - directly verified
      }
    ],
    guidelinesEn: [
      "Drink 1.5 - 2.5 Liters of water throughout the day.",
      "Get plenty of sunlight in the morning.",
      "Consistent routine creates the real magic of growth!",
      "Focus on outdoor physical games (45-60 mins daily)."
    ],
    guidelinesHi: [
      "दिनभर में कम से कम 1.5 से 2.5 लीटर पानी पिलाएं।",
      "सुबह के समय थोड़ी धूप अवश्य लें।",
      "सकारात्मक आदतें ही जीवन का मजबूत आधार बनती हैं।",
      "रोजाना 45-60 मिनट आउटडोर खेलकूद जरूरी है।"
    ],
    forbiddenEn: ["Cold drinks", "High sodium Chips", "Chocolates & Sugary candies", "Oily burgers & fast foods", "Late-night screen time"],
    forbiddenHi: ["कोल्ड ड्रिंक्स", "चिप्स और कुरकुरे", "चॉकलेट्स और ज़्यादा मीठा", "फास्ट फूड व बर्गर", "देर रात तक मोबाइल/टीवी देखना"]
  },

  [PlanType.HEALTHY_FITNESS]: {
    nameEn: "Healthy Fitness Routine Plan",
    nameHi: "हेल्दी फिटनेस डेली रुटीन",
    targetEn: "Healthy & Fit Lifestyle, Stable Weight, Good Energy, Active Lifestyle",
    targetHi: "स्वस्थ और फिट रहना, स्थिर वजन, बेहतरीन एनर्जी, स्वास्थ्य का निर्माण",
    tasks: [
      {
        id: "fit-0600-water",
        time: "06:00 AM",
        hour: 6,
        minute: 0,
        titleEn: "Morning Hydration",
        titleHi: "सुबह उठते ही हाइड्रेशन",
        descriptionEn: "Drink 1-2 glasses of warm lukewarm water to boost metabolism.",
        descriptionHi: "सुबह उठते ही 1-2 गिलास गुनगुना पानी पिएं। शरीर की शुद्धि के लिए।",
        isHerbalifeProduct: false,
        noCameraNeeded: false,
        healthyAlternatives: ["Water"],
      },
      {
        id: "fit-0630-afresh",
        time: "06:30 AM",
        hour: 6,
        minute: 30,
        titleEn: "Online Wellness Session + Afresh",
        titleHi: "सुबह की क्लास + अफ्रेश 1 स्कूप",
        descriptionEn: "Join Herbalife online class & motivation session + Drink 1 scoop Afresh energy drink.",
        descriptionHi: "हर्बालाइफ ऑनलाइन वेलनेस क्लास और योग सेशन + अफ्रेश एनर्जी ड्रिंक 1 स्कूप।",
        isHerbalifeProduct: true,
        requiredProduct: "Afresh",
        noCameraNeeded: false,
      },
      {
        id: "fit-0730-shake",
        time: "07:30 AM",
        hour: 7,
        minute: 30,
        titleEn: "Healthy Breakfast (F1 + ShakeMate)",
        titleHi: "हेल्दी ब्रेकफास्ट (F1 + शेकमेंट)",
        descriptionEn: "Drink Formula 1 (1-2 scoops) + ShakeMate (1 scoop) blended in water or low-fat milk.",
        descriptionHi: "फार्मूला 1 [1-2 स्कूप] + शेकमेंट [1 स्कूप] पानी या मलाई रहित दूध के साथ।",
        isHerbalifeProduct: true,
        requiredProduct: "Formula 1", // Primary Herbalife marker
        noCameraNeeded: false,
      },
      {
        id: "fit-1030-snack",
        time: "10:30 AM",
        hour: 10,
        minute: 30,
        titleEn: "Mid-Morning Nutrition",
        titleHi: "मिड-मॉर्निंग न्यूट्रिशन",
        descriptionEn: "Eat any seasonal fresh fruit and stay hydrated.",
        descriptionHi: "कोई भी ताज़ा मौसमी फल खाएं और भरपूर पानी पिएं।",
        isHerbalifeProduct: false,
        noCameraNeeded: false,
        healthyAlternatives: ["Apple", "Orange", "Papaya", "Pomegranate"],
      },
      {
        id: "fit-1300-lunch",
        time: "01:00 PM",
        hour: 13,
        minute: 0,
        titleEn: "Balanced Lunch",
        titleHi: "दोपहर का संतुलित भोजन",
        descriptionEn: "Eat 2-3 Roti + Dal + Sabzi + Green Salad + Curd.",
        descriptionHi: "2-3 रोटी + दाल + मौसमी हरी सब्जी + सलाद + ताज़ा दही।",
        isHerbalifeProduct: false,
        noCameraNeeded: false,
        healthyAlternatives: ["Brown Rice with Dal/Vegs", "Wheaty lunch platter"],
      },
      {
        id: "fit-1400-afresh",
        time: "02:00 PM",
        hour: 14,
        minute: 0,
        titleEn: "Refresh & Hydration (Afresh)",
        titleHi: "दोपहर रिफ्रेश्नमेंट (अफ्रेश)",
        descriptionEn: "Drink 1 scoop of Afresh energy drink to fight afternoon lethargy.",
        descriptionHi: "दोपहर की सुस्ती मिटाने के लिए गरम पानी में 1 स्कूप अफ्रेश पिएं।",
        isHerbalifeProduct: true,
        requiredProduct: "Afresh",
        noCameraNeeded: false,
      },
      {
        id: "fit-1600-snack",
        time: "04:00 PM",
        hour: 16,
        minute: 0,
        titleEn: "Evening Healthy Snack",
        titleHi: "शाम का हेल्दी स्नैक",
        descriptionEn: "Eat roasted Makhana, Sprouts, dry fruits, or Chana.",
        descriptionHi: "भुना मखाना, स्प्राउट्स, भुना चना या एक मुट्ठी हेल्दी सूखे मेवे खाएं।",
        isHerbalifeProduct: false,
        noCameraNeeded: false,
        healthyAlternatives: ["Sprouts", "Makhana", "Dry Fruits", "Roasted Chana"],
      },
      {
        id: "fit-1700-class",
        time: "05:00 PM",
        hour: 17,
        minute: 0,
        titleEn: "Evening Online Club + Afresh",
        titleHi: "शाम की वेलनेस क्लास + अफ्रेश",
        descriptionEn: "Join online fitness session with lightweight stretching exercises + 1 scoop Afresh.",
        descriptionHi: "ऑनलाइन हर्बालाइफ शाम का फिटनेस सेशन + 1 स्कूप गरमा-गरम अफ्रेश।",
        isHerbalifeProduct: true,
        requiredProduct: "Afresh",
        noCameraNeeded: false,
      },
      {
        id: "fit-1800-activity",
        time: "06:00 PM",
        hour: 18,
        minute: 0,
        titleEn: "Evening Activity",
        titleHi: "शाम की गतिविधि (वॉक/योग)",
        descriptionEn: "Spend 30 mins in brisk walking, Yoga, cycling, or physical mobility exercise.",
        descriptionHi: "30 मिनट के लिए योग, शांत वॉक या साइकिलिंग करें।",
        isHerbalifeProduct: false,
        noCameraNeeded: false,
      },
      {
        id: "fit-2000-dinner",
        time: "08:00 PM",
        hour: 20,
        minute: 0,
        titleEn: "Light Dinner",
        titleHi: "हल्का रात्रि भोजन (डिनर)",
        descriptionEn: "Eat 2 Roti + Light Sabzi + Dal, Paneer, or Tofu + Green Salad.",
        descriptionHi: "2 रोटी + हल्की सब्जी + कटोरी दाल/पनीर/टोफू + सलाद खिरावटी।",
        isHerbalifeProduct: false,
        noCameraNeeded: false,
        healthyAlternatives: ["Soup with Sautéed Vegs", "Dalia", "Khichdi"],
      },
      {
        id: "fit-2200-night",
        time: "10:00 PM",
        hour: 22,
        minute: 0,
        titleEn: "Night Warm Drink",
        titleHi: "सोने से पहले की तृप्ति",
        descriptionEn: "Drink warm water or warm milk plus 4-5 soaked almonds.",
        descriptionHi: "गुनगुना दूध या गरम पानी + 4-5 भीगे बादाम चबाकर खाएं।",
        isHerbalifeProduct: false,
        noCameraNeeded: false,
        healthyAlternatives: ["Warm milk", "Warm water", "Almonds"],
      },
      {
        id: "fit-2230-sleep",
        time: "10:30 PM",
        hour: 22,
        minute: 30,
        titleEn: "Sleep & Muscle Recovery",
        titleHi: "नींद और हेल्दी रिकवरी",
        descriptionEn: "Keep mobile completely away and sleep soundly for 7-8 hours.",
        descriptionHi: "मोबाइल को दूरी पर रखें और 7 से 8 घंटे की भरपूर गहरी नींद लें।",
        isHerbalifeProduct: false,
        noCameraNeeded: true, // Sleep
      }
    ],
    guidelinesEn: [
      "Drink 3 - 4 liters of water daily to keep organs hydrated.",
      "Prefer homemade fresh meals over outside deliveries.",
      "Commit to 30-45 minutes of daily workout/exercise.",
      "Check progress regularly. Consistency delivers success!"
    ],
    guidelinesHi: [
      "दिनभर में कम से कम 3 से 4 लीटर पानी जरूर पिएं।",
      "घर का बना शुद्ध ताज़ा भोजन ही खाएं।",
      "रोजाना 30-45 मिनट शारीरिक रूप से एक्टिव रहें।",
      "धैर्य रखें और अपनी आदतों पर फोकस करें।"
    ],
    forbiddenEn: ["Cold sodas and canned juice", "Deep-fried snacks or junk foods", "Sweets & desserts with heavy refined sugar", "Maida and processed bakery goods", "Oily heavy dinners"],
    forbiddenHi: ["ठंडे पेय/कोल्ड ड्रिंक्स", "तैलीय तले-भुने स्नैक्स", "ज़्यादा मीठा और परिष्कृत चीनी", "मैदा और बेकरी उत्पाद", "देर रात अधिक भारी भोजन"]
  },

  [PlanType.MUSCLE_BUILDING]: {
    nameEn: "Herbalife Muscle Building Daily Routine",
    nameHi: "हर्बालाइफ मसल बिल्डिंग डेली रुटीन",
    targetEn: "Lean Muscle Gain, High Strength, Healthy Muscle Recovery (100% Vegetarian)",
    targetHi: "लीन मसल गेन + स्ट्रेंथ + मसल रिकवरी (100% शाकाहारी)",
    tasks: [
      {
        id: "muscle-0600-water",
        time: "06:00 AM",
        hour: 6,
        minute: 0,
        titleEn: "Morning Hydration",
        titleHi: "मॉर्निंग हाइड्रेशन",
        descriptionEn: "Drink 2 glasses of pure water (normal or lukewarm) immediately on waking.",
        descriptionHi: "सुबह उठते ही 2 गिलास सादा या हल्का गुनगुना पानी पिएं। पाचन बेहतर होता है।",
        isHerbalifeProduct: false,
        noCameraNeeded: false,
        healthyAlternatives: ["Water"],
      },
      {
        id: "muscle-0630-energy",
        time: "06:30 AM",
        hour: 6,
        minute: 30,
        titleEn: "Energy Startup (Afresh + Fruit)",
        titleHi: "हर्बालाइफ एनर्जी स्टार्ट (अफ्रेश)",
        descriptionEn: "Drink hot water containing 1 scoop Afresh + Eat 1 banana or 2-3 sweet dates.",
        descriptionHi: "अफ्रेश 1 स्कूप गरम पानी में + 1 केला या 2-3 खजूर खाएं (वर्कआउट से पहले)।",
        isHerbalifeProduct: true,
        requiredProduct: "Afresh",
        noCameraNeeded: false,
      },
      {
        id: "muscle-0700-workout",
        time: "07:00 AM",
        hour: 7,
        minute: 0,
        titleEn: "Muscle Building Resistance Activity",
        titleHi: "हर्बालाइफ फिटनेस एक्टिविटी (वर्कआउट)",
        descriptionEn: "Do 60 minutes intensity workout (resistance, compound training, core, stretch).",
        descriptionHi: "60 मिनट के लिए ऑनलाइन क्लास क्लब ज्वाइन करें या वेट ट्रेनिंग/एक्टिव वर्कआउट करें।",
        isHerbalifeProduct: false,
        noCameraNeeded: false,
      },
      {
        id: "muscle-0815-shake",
        time: "08:15 AM",
        hour: 8,
        minute: 15,
        titleEn: "Post Workout Muscle Shake (F1 + PPP + ShakeMate)",
        titleHi: "पोस्ट वर्कआउट मसल शेक (F1+PPP+SM)",
        descriptionEn: "Blend Formula 1 (3 scoops) + PPP (2 scoops) + ShakeMate (2 scoops) in milk or water.",
        descriptionHi: "मसल रिकवरी शेक - फार्मूला 1 [3 स्कूप] + प्रोटीन पाउडर (PPP) [2 स्कूप] + शेकमेंट [2 स्कूप] + दूध या पानी।",
        isHerbalifeProduct: true,
        requiredProduct: "Personalised Protein Powder", // Primary high-protein marker
        noCameraNeeded: false,
      },
      {
        id: "muscle-0900-breakfast",
        time: "09:00 AM",
        hour: 9,
        minute: 0,
        titleEn: "High Protein Breakfast",
        titleHi: "हाई प्रोटीन ब्रेकफास्ट",
        descriptionEn: "Eat Paneer Bhurji + 2 Roti, OR Moong Dal Chilla + Yogurt, OR Oats + Nuts + Milk.",
        descriptionHi: "शाकाहारी नाश्ता विकल्प: पनीर भुर्जी + 2 रोटी अथवा मूंग दाल चीला + दही या ओट्स।",
        isHerbalifeProduct: false,
        noCameraNeeded: false,
        healthyAlternatives: ["Paneer Bhurji with Roti", "Moong Dal Chilla", "Oats Bowl with Milk"],
      },
      {
        id: "muscle-1030-snack",
        time: "10:30 AM",
        hour: 10,
        minute: 30,
        titleEn: "Bulk Mid-Morning Snack + Afresh",
        titleHi: "मिड मॉर्निंग स्नैक + अफ्रेश 1 स्कूप",
        descriptionEn: "Eat Banana / Mango / Chiku + Peanut butter sandwich + Almonds/Raisins + 1 scoop Afresh.",
        descriptionHi: "केला या चीकू + पीनट बटर सैंडविच + बादाम-किशमिश + 1 स्कूप गरम-गरम अफ्रेश।",
        isHerbalifeProduct: true,
        requiredProduct: "Afresh",
        noCameraNeeded: false,
      },
      {
        id: "muscle-1300-lunch",
        time: "01:00 PM",
        hour: 13,
        minute: 0,
        titleEn: "High Protein Vegetarian Lunch",
        titleHi: "हाई प्रोटीन दोपहर लंच (शाकाहारी)",
        descriptionEn: "Eat 4-5 Roti + Dal / Rajma / Chole / Moong Dal + Soya chunks or Paneer + Green Salad + Curd.",
        descriptionHi: "भारी लंच - 4-5 रोटी + गाढ़ी दाल/राजमा/छोले + पनीर/सोया चंक्स सब्जी + हरी सलाद + दही।",
        isHerbalifeProduct: false,
        noCameraNeeded: false,
        healthyAlternatives: ["Rice Paneer-Dal meal", "Thick Dal-Roti platter"],
      },
      {
        id: "muscle-1530-snack",
        time: "03:30 PM",
        hour: 15,
        minute: 30,
        titleEn: "Energy Fuel (Makhana / Coconut Water)",
        titleHi: "एनर्जी स्नैक (मखाना)",
        descriptionEn: "Eat roasted chickpeas, peanuts, and makhana + 1 fresh coconut water.",
        descriptionHi: "भुना चना, मूंगफली, भुने मखाने और साथ में ताज़ा नारियल पानी।",
        isHerbalifeProduct: false,
        noCameraNeeded: false,
        healthyAlternatives: ["Peanuts", "Makhana", "Coconut Water"],
      },
      {
        id: "muscle-1730-class",
        time: "05:30 PM",
        hour: 17,
        minute: 30,
        titleEn: "Evening Protein Shake or Class Mix",
        titleHi: "शाम की वेलनेस क्लास + पीपीपी शेक",
        descriptionEn: "Online wellness session OR consume PPP light protein shake + sprouts/fruits.",
        descriptionHi: "सलाहकार के साथ ऑनलाइन क्लास + प्रोटीन शेक (Personalised Protein Powder) या फार्मूला 1 लाइट शेक + फल व मखाना।",
        isHerbalifeProduct: true,
        requiredProduct: "Personalised Protein Powder",
        noCameraNeeded: false,
      },
      {
        id: "muscle-2000-dinner",
        time: "08:00 PM",
        hour: 20,
        minute: 0,
        titleEn: "Hyper Dinner",
        titleHi: "डिनर (प्रोटीन युक्त भोजन)",
        descriptionEn: "Eat 3-4 Roti or brown rice + Paneer / Tofu / Soya Chunks + Green leafy Vegetables + High Salad.",
        descriptionHi: "3-4 रोटी या चावल + भरपूर पनीर/टोफू/सोया सब्जी + हरी सब्जियां + ताज़ी सलाद प्लेट।",
        isHerbalifeProduct: false,
        noCameraNeeded: false,
        healthyAlternatives: ["Roti with Paneer", "Soya chunk curry with Rice"],
      },
      {
        id: "muscle-2200-night",
        time: "10:00 PM",
        hour: 22,
        minute: 0,
        titleEn: "Pre-Sleep Rebuild Fuel",
        titleHi: "सोने से पहले की ताकत",
        descriptionEn: "Drink 1 glass warm milk + 5 almonds + 2 walnuts for nocturnal muscle recovery.",
        descriptionHi: "सोने से पहले 1 गिलास गुनगुना दूध + 5 बादाम + 2 अखरोट चबाकर खाएं।",
        isHerbalifeProduct: false,
        noCameraNeeded: false,
        healthyAlternatives: ["Milk", "Almonds"],
      },
      {
        id: "muscle-2230-sleep",
        time: "10:30 PM",
        hour: 22,
        minute: 30,
        titleEn: "Anabolic Sleep & Deep Recovery",
        titleHi: "मजबूत नींद और गहरी रिकवरी",
        descriptionEn: "Sleep 7-8 hours soundly in dark room. Muscle protein synthesis peaks during deep rest.",
        descriptionHi: "7-8 घंटे की गहरी नींद लें। नींद में ही शरीर नई कोशिकाओं और मसल्स का पुनर्निर्माण करता है।",
        isHerbalifeProduct: false,
        noCameraNeeded: true, // Sleep
      }
    ],
    guidelinesEn: [
      "Drink 4 - 5 liters of water daily to keep hard muscles fully hydrated.",
      "Track daily protein targets (aim for 1.5g per kg bodyweight).",
      "Ensure to progressive overload in workouts safely.",
      "Never skip scheduled meals or protein shakes!"
    ],
    guidelinesHi: [
      "रोजाना 4 से 5 लीटर पानी पिएं ताकि थकी मसल्स रिकवर रहें।",
      "हमेशा अपने प्रोटीन की मात्रा का ध्यान रखें।",
      "वर्कआउट में निरंतर प्रोग्रेसिव प्रयास करें।",
      "कभी भी दिन का मुख्य भोजन या प्रोटीन शेक स्किप न करें।"
    ],
    forbiddenEn: ["Cold sodas and sugary carbonated drinks", "Deep-refined sweet treats or white sugars", "Dehydrating alcohol & smoking habits", "Refined flour (Maida) bakery breads", "Processed chips & salted namkeen"],
    forbiddenHi: ["कोल्ड ड्रिंक्स व सोडा", "सफेद चीनी और ज़्यादा मीठा खाना", "धूम्रपान और नशीले पदार्थ", "मैदा की रोटियां या ब्रेड", "नमकीन और पैकेटबंद चिप्स"]
  },

  [PlanType.WEIGHT_LOSS]: {
    nameEn: "Weight Loss Diet Plan",
    nameHi: "वजन घटाने का डाइट प्लान",
    targetEn: "Effective, Scientifically Sustainable Weight Loss, Belly Fat Burning",
    targetHi: "प्रभावी और टिकाऊ वजन घटाना, अनावश्यक फैट बर्न करना",
    tasks: [
      {
        id: "loss-0600-water",
        time: "06:00 AM",
        hour: 6,
        minute: 0,
        titleEn: "Morning Hydration",
        titleHi: "सुबह की हाइड्रेशन",
        descriptionEn: "Drink 1 glass of lukewarm water to kickstart fat burning.",
        descriptionHi: "सुबह उठते ही 1 गिलास गुनगुना पानी पिएं। खाली पेट शरीर को एक्टिव करने के लिए।",
        isHerbalifeProduct: false,
        noCameraNeeded: false,
        healthyAlternatives: ["Water"],
      },
      {
        id: "loss-0630-club",
        time: "06:30 AM",
        hour: 6,
        minute: 30,
        titleEn: "Morning Online Club + Afresh",
        titleHi: "सुबह क्लब ज्वाइन + वार्म-अप + अफ्रेश",
        descriptionEn: "Online Herbalife session + 30-45 mins fat-loss workout + Drink hot Afresh.",
        descriptionHi: "ऑनलाइन हर्बालाइफ क्लब ज्वाइन करें + कार्डियो वर्कआउट + गरमा गरम अफ्रेश।",
        isHerbalifeProduct: true,
        requiredProduct: "Afresh",
        noCameraNeeded: false,
      },
      {
        id: "loss-0730-shake",
        time: "07:30 AM",
        hour: 7,
        minute: 30,
        titleEn: "Fat Loss Nutritional Shake (F1 + SM + Fiber)",
        titleHi: "न्यूट्रीशनल फैट बर्न शेक (F1+SM+Fiber)",
        descriptionEn: "Drink Formula 1 (3 spoons) + ShakeMate (2 spoons) + Active Fiber Complex (1 spoon) in 400ml water.",
        descriptionHi: "फार्मूला 1 [3 चम्मच] + शेकमेंट [2 चम्मच] + एक्टिव फाइबर कॉम्प्लेक्स [1 चम्मच] 400ml पानी में मिलाकर पिएं।",
        isHerbalifeProduct: true,
        requiredProduct: "Formula 1",
        noCameraNeeded: false,
      },
      {
        id: "loss-1030-snack",
        time: "10:30 AM",
        hour: 10,
        minute: 30,
        titleEn: "Mid-Morning Calorie-Deficit Snack + Afresh",
        titleHi: "मिड-मॉर्निंग फ्रूट्स + 10 मिनट बाद अफ्रेश",
        descriptionEn: "Eat any fresh available low-calorie fruit. After 10 mins, drink 1 scoop of hot Afresh.",
        descriptionHi: "कोई भी मौसमी फल खाएं। उसके ठीक 10 मिनट बाद 1 कप गरम पानी में अफ्रेश बनाकर पिएं।",
        isHerbalifeProduct: true,
        requiredProduct: "Afresh",
        noCameraNeeded: false,
      },
      {
        id: "loss-1300-lunch",
        time: "01:00 PM",
        hour: 13,
        minute: 0,
        titleEn: "Thermic Lunch",
        titleHi: "दोपहर का संतुलित आहार",
        descriptionEn: "Eat 2 Roti + Green Vegetables + Full Bowl Green Salad + Curd (Healthy Portioning).",
        descriptionHi: "2 सादी चपाती + हरी सब्जी + 1 बड़ी प्लेट हरी सलाद + कम वसा वाला दही।",
        isHerbalifeProduct: false,
        noCameraNeeded: false,
        healthyAlternatives: ["1 Chapatis with Dal-Veg-Salad", "Salad-Yogurt plate"],
      },
      {
        id: "loss-1400-afresh",
        time: "02:00 PM",
        hour: 14,
        minute: 0,
        titleEn: "Fat Burn Afresh Dose (2 spoons)",
        titleHi: "दोपहर हर्बल एनर्जी ड्रिंक (अफ्रेश)",
        descriptionEn: "Drink hot water with 2 spoons of Afresh to mobilize lipid chains.",
        descriptionHi: "थकान भगाने और मेटाबॉलिज्म तेज करने के लिए 2 चम्मच अफ्रेश गरम पानी में पिएं।",
        isHerbalifeProduct: true,
        requiredProduct: "Afresh",
        noCameraNeeded: false,
      },
      {
        id: "loss-1600-snack",
        time: "04:00 PM",
        hour: 16,
        minute: 0,
        titleEn: "Evening High Fiber Snack",
        titleHi: "शाम का हल्का सलाद/मखाना",
        descriptionEn: "Eat crisp cucumber, carrot salad, or roasted Makhana.",
        descriptionHi: "हरी ककड़ी, खीरा, मौसमी सलाद या मुट्ठी भर भुना मखाना खाएं।",
        isHerbalifeProduct: false,
        noCameraNeeded: false,
        healthyAlternatives: ["Salad", "Cucumber", "Makhana"],
      },
      {
        id: "loss-1700-club",
        time: "05:00 PM",
        hour: 17,
        minute: 0,
        titleEn: "Evening Session + Afresh",
        titleHi: "शाम की वेलनेस क्लास + अफ्रेश वार्म-अप",
        descriptionEn: "Join counselor-led evening club + easy physical workout session + Warm Afresh.",
        descriptionHi: "शाम का मोटिवेशन और फिटनेस सेशन + गरम पानी में 1 स्कूप अफ्रेश।",
        isHerbalifeProduct: true,
        requiredProduct: "Afresh",
        noCameraNeeded: false,
      },
      {
        id: "loss-2000-dinner",
        time: "08:00 PM",
        hour: 20,
        minute: 0,
        titleEn: "Calorie Deficit Dinner",
        titleHi: "वजन घटाने का डिनर (शेक या खिचड़ी)",
        descriptionEn: "Day 1: Formula 1 + ShakeMate Blend. Day 2: Light Moong Dal Khichdi. STRICTLY NO ROTI AT NIGHT!",
        descriptionHi: "दिन 1: फार्मूला 1 शेक। दिन 2: पतली मूंग दाल खिचड़ी। रात में चपाती / रोटी खाना सख्त मना है।",
        isHerbalifeProduct: true,
        requiredProduct: "Formula 1", // Primary marker
        noCameraNeeded: false,
      },
      {
        id: "loss-2200-sleep",
        time: "10:00 PM",
        hour: 22,
        minute: 0,
        titleEn: "Deep Rest Night Prep",
        titleHi: "आराम करें (सोने का समय)",
        descriptionEn: "Time to rest. Keep system hydrated and go sleeping.",
        descriptionHi: "सोने का समय। रात में शांति से सोएं व दिमाग को आराम दें। It helps fat loss.",
        isHerbalifeProduct: false,
        noCameraNeeded: true, // Sleep
      }
    ],
    guidelinesEn: [
      "Drink 8 - 10 Glasses (approx 3 liters) of pure water daily.",
      "Stay strictly in a calorie deficit under counselor supervision.",
      "Never eat wheat Roti/rice or oily items at night.",
      "Perform steps or physical brisk walks (7K-10K steps daily)."
    ],
    guidelinesHi: [
      "दिनभर में कम से कम 8 से 10 गिलास (3 लीटर) पानी पिएं।",
      "रात्रि भोजन रात 8:30 बजे से पहले अवश्य खाएं।",
      "वजन घटाने के दौरान रात में रोटी/हैवी डिश खाना बंद करें।",
      "रोजाना 7000 से 10000 कदम पैदल चलें।"
    ],
    forbiddenEn: ["Cold sodas and sweetened drinks", "Sweets & junk desserts", "Fried processed chips or deep pakoras", "Wheat flatbreads (Roti) at night", "Eating after 9:00 PM (late night snacking)"],
    forbiddenHi: ["कोल्ड ड्रिंक्स व डिब्बाबंद जूस", "मिठाइयां व मीठा खाना", "तला-भुना जंक फूड व समोसे", "रात के भोजन में चपाती/रोटी खाना", "रात 9 बजे के बाद स्नैक्स खाना"]
  },

  [PlanType.WEIGHT_GAIN]: {
    nameEn: "Healthy Weight Gain Diet Plan",
    nameHi: "वजन बढ़ाने का डाइट पाना",
    targetEn: "Healthy, Calorie Dense Wholesome Weight Gain, Muscle Density Boost",
    targetHi: "हेल्दी वेट गेन, वजनी मांसपेशियों की मजबूत ग्रोथ",
    tasks: [
      {
        id: "gain-0600-water",
        time: "06:00 AM",
        hour: 6,
        minute: 0,
        titleEn: "Morning Warm Hydration",
        titleHi: "सुबह की हाइड्रेशन",
        descriptionEn: "Drink 1 glass of lukewarm normal water immediately on waking up.",
        descriptionHi: "सुबह आँख खुलते ही 1 गिलास गुनगुना पानी पिएं। पेट साफ करने व भूख बढ़ाने के लिए।",
        isHerbalifeProduct: false,
        noCameraNeeded: false,
        healthyAlternatives: ["Water"],
      },
      {
        id: "gain-0630-club",
        time: "06:30 AM",
        hour: 6,
        minute: 30,
        titleEn: "Morning Online Session",
        titleHi: "मॉर्निंग क्लास - योग व स्ट्रेच",
        descriptionEn: "Join positive morning community wellness sessions for motivation & health.",
        descriptionHi: "सुबह ऑनलाइन या कम्युनिटी के साथ मोटिवेशन और वेलनेस सेशन जॉइन करें।",
        isHerbalifeProduct: false,
        noCameraNeeded: false,
      },
      {
        id: "gain-0700-afresh",
        time: "07:00 AM",
        hour: 7,
        minute: 0,
        titleEn: "Metabolism Booster Afresh Dose",
        titleHi: "मेटाबॉलिज्म बूस्टर (अफ्रेश)",
        descriptionEn: "Drink 1 scoop of hot Afresh energy drink to boost food digestion potential.",
        descriptionHi: "भूख तेज करने और ऊर्जा बढ़ाने के लिए 1 स्कूप अफ्रेश गरम पानी में पिएं।",
        isHerbalifeProduct: true,
        requiredProduct: "Afresh",
        noCameraNeeded: false,
      },
      {
        id: "gain-0800-breakfast",
        time: "08:00 AM",
        hour: 8,
        minute: 0,
        titleEn: "Calorie-Dense Breakfast (F1 + ShakeMate)",
        titleHi: "वजन बढ़ानेवाला नाश्ता (F1 + SM)",
        descriptionEn: "Drink Formula 1 (3 scoops) + ShakeMate (2 scoops) blended in full cream milk.",
        descriptionHi: "नाश्ता - फार्मूला-1 [3 स्कूप] + शेकमेंट [2 स्कूप] फुल मलाई वाले गरम दूध के साथ।",
        isHerbalifeProduct: true,
        requiredProduct: "Formula 1",
        noCameraNeeded: false,
      },
      {
        id: "gain-1000-snack",
        time: "10:00 AM",
        hour: 10,
        minute: 0,
        titleEn: "Calorie Snack (2 Bananas)",
        titleHi: "मिड-मॉर्निंग हेवी फ्रूट स्नैक",
        descriptionEn: "Eat 2 bananas, or sweet Chiku, or seasonal mangoes.",
        descriptionHi: "ताकत के लिए 2 पके केले, चीकू या कोई मीठा मौसमी फल खाएं।",
        isHerbalifeProduct: false,
        noCameraNeeded: false,
        healthyAlternatives: ["Banana", "Chiku", "Mango", "Dates"],
      },
      {
        id: "gain-1200-lunch",
        time: "12:00 PM",
        hour: 12,
        minute: 0,
        titleEn: "Wholesome Heavy Lunch",
        titleHi: "दोपहर का भारी भोजन",
        descriptionEn: "Eat 4 simple Roti + Green Vegetables + Bowl of Salad + Thick Curd + Ghee.",
        descriptionHi: "दोपहर भोजन - 4 चपाती + मौसमी सब्जी + सलाद + कटोरी भर गाढ़ा दही + देसी घी।",
        isHerbalifeProduct: false,
        noCameraNeeded: false,
        healthyAlternatives: ["Rice with Dal-Ghee-Vegs", "Heavy standard lunch"],
      },
      {
        id: "gain-1300-afresh",
        time: "01:00 PM",
        hour: 13,
        minute: 0,
        titleEn: "Post Lunch Afresh Digestion Dose",
        titleHi: "दोपहर पाचन बूस्टर (अफ्रेश)",
        descriptionEn: "Drink hot water with 1 scoop of Afresh to digest the heavy lunch and support metabolic pathways.",
        descriptionHi: "लंच पचाने और सुस्ती दूर करने के लिए गरम पानी में 1 स्कूप अफ्रेश लें।",
        isHerbalifeProduct: true,
        requiredProduct: "Afresh",
        noCameraNeeded: false,
      },
      {
        id: "gain-1600-snack",
        time: "04:00 PM",
        hour: 16,
        minute: 0,
        titleEn: "Evening Healthy Snack",
        titleHi: "शाम की चाय + हेल्दी स्नैक्स",
        descriptionEn: "Enjoy light tea paired with high-calorie healthy grain baked snacks.",
        descriptionHi: "शाम का हल्का नाश्ता - चाय के साथ भुने स्नैक्स, बिस्कुट या मखाना लें।",
        isHerbalifeProduct: false,
        noCameraNeeded: false,
        healthyAlternatives: ["Tea with Roasted Grain", "Makhana with nuts"],
      },
      {
        id: "gain-1700-nutrition",
        time: "05:00 PM",
        hour: 17,
        minute: 0,
        titleEn: "Evening High Protein Sprouts",
        titleHi: "शाम पोषण (स्प्राउट्स व मेवे)",
        descriptionEn: "Eat detailed sprouts (Moong, Chana) & soaked healthy dry fruits (almonds, raisins).",
        descriptionHi: "शाम का एक्स्ट्रा प्रोटीन - स्प्राउट्स (मूंग, चना) + भीगे हुए सूखे मेवे खाएं।",
        isHerbalifeProduct: false,
        noCameraNeeded: false,
        healthyAlternatives: ["Sprouts", "Moong/Chana bowl", "Dry fruits"],
      },
      {
        id: "gain-2000-dinner",
        time: "08:00 PM",
        hour: 20,
        minute: 0,
        titleEn: "Heavy Dinner",
        titleHi: "रात का भोजन (डिनर)",
        descriptionEn: "Eat 3 Roti + Fresh Green Subzi + Dal topped with pure Desi Ghee.",
        descriptionHi: "रात्रि भोजन - 3 सादी चपाती लगायी हुई घी + पौष्टिक दाल + हरी मौसमी सब्जी।",
        isHerbalifeProduct: false,
        noCameraNeeded: false,
        healthyAlternatives: ["Rice-Dal bowl with Ghee", "Roti with Paneer"],
      },
      {
        id: "gain-2200-sleep",
        time: "10:00 PM",
        hour: 22,
        minute: 0,
        titleEn: "Rest & Sleep Recovery",
        titleHi: "आराम (सोने का समय)",
        descriptionEn: "Time for deep skeletal rest. Sleep soundly for 8 hours for weight gain progression.",
        descriptionHi: "समय पर सोएं। वजन बढ़ाने और अच्छी सेहत के लिए 7-8 घंटे की गहरी नींद सबसे ज़रूरी है।",
        isHerbalifeProduct: false,
        noCameraNeeded: true, // Sleep
      }
    ],
    guidelinesEn: [
      "Drink approx 10 glasses of clean water throughout the day.",
      "Stay consistent, be extremely patient with body tissues, and trust the process.",
      "Add healthy fats like Desi Ghee, butter, or almonds to meals.",
      "Never skip any of the key meals or shakes!"
    ],
    guidelinesHi: [
      "दिनभर में कम से कम 10 गिलास (3 लीटर) स्वच्छ पानी पीते रहें।",
      "धीरज रखें, नियमित रहें और अपनी डाइट का ख्याल रखें।",
      "भोजन में स्वस्थ वसा जैसे देसी घी, मक्खन, बादाम इस्तेमाल करें।",
      "अपने दिन का कोई भी जरूरी भोजन या शेक मिस न करें!"
    ],
    forbiddenEn: ["Salty junk crisps or namkeen packet food", "Bakery items made with refined flour (Maida)", "Deep greasy outside fried snacks", "Carbonated chilled cold chemical juices"],
    forbiddenHi: ["सॉल्टी चिप्स और नमकीन पैकेट", "मैदा की बनी चीजें, पाव या ब्रेड", "बाहर का अधिक तला-भुना मसालेदार भोजन", "कोल्ड ड्रिंक्स और पैक्ड केमिकल वाले जूस"]
  }
};
